### PR TITLE
All pulls for today

### PR DESCRIPTION
**Pull request by RUTAN47**
Link to my deployed project:

My reflections on how this week's project turned out:

Things I'd like to have clarified or explained in more detail:

### CODE REVIEW

**Review by ericaglimsholt — CHANGES_REQUESTED** [review]
Hi! I need a Netlify link and also the names of you who have done this assignment

**Comment by RUTAN47** [comment]
Hej Erica,

Here is the link.

https://5e3fc5526e99cd823c725c95--jolly-swirles-a68592.netlify.com/

Johan and William has done the project.

**Review by ericaglimsholt — CHANGES_REQUESTED** [review]
Hi both of you! Sorry for the late review. It takes longer time when we can't review it when we look at it for the first time. Please make sure that the link is included next time and you will get a review right away :) 

But sadly I can't make any orders in your project. It would be good if you can take a look at it and update it. Then I will make a full review and hopefully add this project as done and approved for you :)

**Review by ericaglimsholt — CHANGES_REQUESTED** [review]
See comment I have you before

**Pull request closed without merging**
